CREATE TABLE DEPARTMENT (
    DEPT_ID NUMBER(5) PRIMARY KEY,
    DEPT_NAME VARCHAR2(50) NOT NULL,
    HOD_NAME VARCHAR2(50)
);

CREATE TABLE STUDENT (
    STUDENT_ID NUMBER(5) PRIMARY KEY,
    STUDENT_NAME VARCHAR2(50) NOT NULL,
    DEPT_ID NUMBER(5) NOT NULL,
    DOB DATE,
    CITY VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(15) UNIQUE,
    EMAIL VARCHAR2(50) UNIQUE,

    CONSTRAINT FK_STUDENT_DEPT
        FOREIGN KEY (DEPT_ID)
        REFERENCES DEPARTMENT(DEPT_ID)
);

CREATE TABLE FACULTY (
    FACULTY_ID NUMBER(5) PRIMARY KEY,
    FACULTY_NAME VARCHAR2(50) NOT NULL,
    DEPT_ID NUMBER(5) NOT NULL,
    DESIGNATION VARCHAR2(30),
    SALARY NUMBER(10,2) CHECK (SALARY > 0),

    CONSTRAINT FK_FACULTY_DEPT
        FOREIGN KEY (DEPT_ID)
        REFERENCES DEPARTMENT(DEPT_ID)
);

CREATE TABLE COURSE (
    COURSE_ID NUMBER(5) PRIMARY KEY,
    COURSE_NAME VARCHAR2(50) NOT NULL,
    DEPT_ID NUMBER(5) NOT NULL,
    FACULTY_ID NUMBER(5),
    CREDITS NUMBER(2) CHECK (CREDITS > 0),

    CONSTRAINT FK_COURSE_DEPT
        FOREIGN KEY (DEPT_ID)
        REFERENCES DEPARTMENT(DEPT_ID),

    CONSTRAINT FK_COURSE_FACULTY
        FOREIGN KEY (FACULTY_ID)
        REFERENCES FACULTY(FACULTY_ID)
);

CREATE TABLE ENROLLMENT (
    ENROLLMENT_ID NUMBER(6) PRIMARY KEY,
    STUDENT_ID NUMBER(5) NOT NULL,
    COURSE_ID NUMBER(5) NOT NULL,
    ENROLL_DATE DATE DEFAULT SYSDATE,
    MARKS NUMBER(5,2) CHECK (MARKS BETWEEN 0 AND 100),

    CONSTRAINT FK_ENROLLMENT_STUDENT
        FOREIGN KEY (STUDENT_ID)
        REFERENCES STUDENT(STUDENT_ID),

    CONSTRAINT FK_ENROLLMENT_COURSE
        FOREIGN KEY (COURSE_ID)
        REFERENCES COURSE(COURSE_ID)
);

ALTER TABLE STUDENT
ADD ADDRESS VARCHAR2(100);

DESC STUDENT;

INSERT INTO DEPARTMENT
VALUES (10, 'Computer Science', 'Dr. Suresh Kumar');

INSERT INTO DEPARTMENT
VALUES (20, 'Electronics', 'Dr. Meena Devi');

INSERT INTO DEPARTMENT
VALUES (30, 'Mechanical', 'Dr. Ravi Shankar');

INSERT INTO DEPARTMENT
VALUES (40, 'Business Administration', 'Dr. Pooja Singh');

INSERT INTO STUDENT
VALUES (101, 'Arun Kumar', 10, TO_DATE('12-05-2004','DD-MM-YYYY'), 'Chennai', '9876543210', 'arun@gmail.com', 'Anna Nagar');

INSERT INTO STUDENT
VALUES (102, 'Priya Sharma', 20, TO_DATE('20-08-2004','DD-MM-YYYY'), 'Bangalore', '9876543211', 'priya@gmail.com', 'Indiranagar');

INSERT INTO STUDENT
VALUES (103, 'Rahul Singh', 10, TO_DATE('03-11-2003','DD-MM-YYYY'), 'Mumbai', '9876543212', 'rahul@gmail.com', 'Andheri');

INSERT INTO STUDENT
VALUES (104, 'Sneha Reddy', 30, TO_DATE('15-02-2004','DD-MM-YYYY'), 'Hyderabad', '9876543213', 'sneha@gmail.com', 'Banjara Hills');

INSERT INTO STUDENT
VALUES (105, 'Karthik Raj', 10, TO_DATE('25-06-2004','DD-MM-YYYY'), 'Chennai', '9876543214', 'karthik@gmail.com', 'Velachery');

INSERT INTO STUDENT
VALUES (106, 'Divya Nair', 40, TO_DATE('09-09-2003','DD-MM-YYYY'), 'Kochi', '9876543215', 'divya@gmail.com', 'Edappally');

INSERT INTO STUDENT
VALUES (107, 'Vijay Kumar', 20, TO_DATE('30-01-2004','DD-MM-YYYY'), 'Hyderabad', '9876543216', 'vijay@gmail.com', 'Kukatpally');

INSERT INTO STUDENT
VALUES (108, 'Anitha Mary', 30, TO_DATE('18-04-2004','DD-MM-YYYY'), 'Puducherry', '9876543217', 'anitha@gmail.com', 'White Town');

INSERT INTO STUDENT
VALUES (109, 'Ramesh Patel', 40, TO_DATE('22-07-2003','DD-MM-YYYY'), 'Bangalore', '9876543218', 'ramesh@gmail.com', 'Whitefield');

INSERT INTO STUDENT
VALUES (110, 'Lakshmi Devi', 10, TO_DATE('11-12-2004','DD-MM-YYYY'), 'Delhi', '9876543219', 'lakshmi@gmail.com', 'Rohini');

INSERT INTO FACULTY
VALUES (201, 'Dr. Ganesh Rao', 10, 'Professor', 95000);

INSERT INTO FACULTY
VALUES (202, 'Dr. Kavya Reddy', 10, 'Associate Professor', 78000);

INSERT INTO FACULTY
VALUES (203, 'Dr. Manoj Kumar', 20, 'Professor', 92000);

INSERT INTO FACULTY
VALUES (204, 'Dr. Deepa Nair', 20, 'Assistant Professor', 60000);

INSERT INTO FACULTY
VALUES (205, 'Dr. Suresh Babu', 30, 'Professor', 90000);

INSERT INTO FACULTY
VALUES (206, 'Dr. Radha Krishnan', 40, 'Associate Professor', 75000);

INSERT INTO COURSE
VALUES (301, 'Database Systems', 10, 201, 4);

INSERT INTO COURSE
VALUES (302, 'Data Structures', 10, 202, 4);

INSERT INTO COURSE
VALUES (303, 'Digital Electronics', 20, 203, 3);

INSERT INTO COURSE
VALUES (304, 'Microprocessors', 20, 204, 3);

INSERT INTO COURSE
VALUES (305, 'Thermodynamics', 30, 205, 4);

INSERT INTO COURSE
VALUES (306, 'Financial Accounting', 40, 206, 3);

INSERT INTO ENROLLMENT VALUES
(5001, 101, 301, TO_DATE('01-06-2025','DD-MM-YYYY'), 88);

INSERT INTO ENROLLMENT VALUES
(5002, 101, 302, TO_DATE('01-06-2025','DD-MM-YYYY'), 76);

INSERT INTO ENROLLMENT VALUES
(5003, 102, 303, TO_DATE('02-06-2025','DD-MM-YYYY'), 65);

INSERT INTO ENROLLMENT VALUES
(5004, 102, 304, TO_DATE('02-06-2025','DD-MM-YYYY'), 71);

INSERT INTO ENROLLMENT VALUES
(5005, 103, 301, TO_DATE('03-06-2025','DD-MM-YYYY'), 92);

INSERT INTO ENROLLMENT VALUES
(5006, 103, 302, TO_DATE('03-06-2025','DD-MM-YYYY'), 58);

INSERT INTO ENROLLMENT VALUES
(5007, 104, 305, TO_DATE('04-06-2025','DD-MM-YYYY'), 80);

INSERT INTO ENROLLMENT VALUES
(5008, 105, 301, TO_DATE('05-06-2025','DD-MM-YYYY'), 95);

INSERT INTO ENROLLMENT VALUES
(5009, 105, 302, TO_DATE('05-06-2025','DD-MM-YYYY'), 84);

INSERT INTO ENROLLMENT VALUES
(5010, 106, 306, TO_DATE('06-06-2025','DD-MM-YYYY'), 69);

INSERT INTO ENROLLMENT VALUES
(5011, 107, 303, TO_DATE('07-06-2025','DD-MM-YYYY'), 73);

INSERT INTO ENROLLMENT VALUES
(5012, 107, 304, TO_DATE('07-06-2025','DD-MM-YYYY'), 60);

INSERT INTO ENROLLMENT VALUES
(5013, 108, 305, TO_DATE('08-06-2025','DD-MM-YYYY'), 77);

INSERT INTO ENROLLMENT VALUES
(5014, 109, 306, TO_DATE('09-06-2025','DD-MM-YYYY'), 82);

INSERT INTO ENROLLMENT VALUES
(5015, 110, 301, TO_DATE('10-06-2025','DD-MM-YYYY'), 55);

INSERT INTO ENROLLMENT VALUES
(5016, 110, 302, TO_DATE('10-06-2025','DD-MM-YYYY'), 67);

COMMIT;

INSERT INTO STUDENT
VALUES (111, 'Test Student', 10, TO_DATE('01-01-2004','DD-MM-YYYY'),
        'Chennai', '9999999999', 'test@gmail.com', 'T Nagar');

ROLLBACK;

UPDATE STUDENT
SET CITY = 'Madurai'
WHERE STUDENT_ID = 101;

SAVEPOINT SP1;

UPDATE STUDENT
SET CITY = 'Coimbatore'
WHERE STUDENT_ID = 101;

ROLLBACK TO SP1;

COMMIT;

DELETE FROM STUDENT
WHERE STUDENT_ID = 111;

ROLLBACK;

SELECT * FROM STUDENT;

SELECT STUDENT_NAME, PHONE, EMAIL, CITY
FROM STUDENT;

SELECT *
FROM STUDENT
WHERE CITY = 'Chennai';

SELECT *
FROM ENROLLMENT
WHERE MARKS > 80;

SELECT *
FROM ENROLLMENT
WHERE MARKS BETWEEN 60 AND 90;

SELECT *
FROM COURSE
WHERE DEPT_ID = 10;

SELECT *
FROM FACULTY
WHERE DESIGNATION = 'Professor';

SELECT *
FROM ENROLLMENT
WHERE MARKS > 70
AND COURSE_ID = 301;

SELECT *
FROM STUDENT
WHERE CITY = 'Chennai'
OR CITY = 'Bangalore';

SELECT *
FROM FACULTY
WHERE NOT DESIGNATION = 'Professor';

SELECT * FROM ENROLLMENT WHERE MARKS = 88;

SELECT * FROM ENROLLMENT WHERE MARKS <> 88;

SELECT * FROM ENROLLMENT WHERE MARKS > 88;

SELECT * FROM ENROLLMENT WHERE MARKS < 88;

SELECT * FROM ENROLLMENT WHERE MARKS >= 88;

SELECT * FROM ENROLLMENT WHERE MARKS <= 88;

SELECT *
FROM STUDENT
WHERE CITY IN ('Chennai', 'Bangalore', 'Hyderabad');

SELECT *
FROM FACULTY
WHERE SALARY BETWEEN 70000 AND 95000;

SELECT *
FROM STUDENT
WHERE STUDENT_NAME LIKE 'A%';

SELECT *
FROM ENROLLMENT
ORDER BY MARKS ASC;

SELECT *
FROM ENROLLMENT
ORDER BY MARKS DESC;

SELECT
    UPPER(STUDENT_NAME) AS UPPER_NAME,
    LOWER(STUDENT_NAME) AS LOWER_NAME
FROM STUDENT;

SELECT
    STUDENT_NAME,
    LENGTH(STUDENT_NAME) AS NAME_LENGTH
FROM STUDENT;

SELECT
    STUDENT_NAME,
    SUBSTR(STUDENT_NAME, 1, 5) AS SHORT_NAME
FROM STUDENT;

SELECT
    ENROLLMENT_ID,
    MARKS,
    ROUND(MARKS / 3) AS ROUND_MARKS
FROM ENROLLMENT;

SELECT
    FACULTY_ID,
    SALARY,
    MOD(SALARY, 10000) AS REMAINDER
FROM FACULTY;

SELECT
    STUDENT_ID,
    DOB,
    TRUNC(MONTHS_BETWEEN(SYSDATE, DOB) / 12) AS AGE_YEARS
FROM STUDENT;

SELECT
    ENROLLMENT_ID,
    ENROLL_DATE,
    ADD_MONTHS(ENROLL_DATE, 6) AS SEMESTER_END
FROM ENROLLMENT;

SELECT
    ENROLLMENT_ID,
    TO_CHAR(ENROLL_DATE, 'DD-MM-YYYY') AS ENROLL_DATE
FROM ENROLLMENT;

SELECT
    ENROLLMENT_ID,
    NVL(MARKS, 0) AS MARKS
FROM ENROLLMENT;

SELECT
    ENROLLMENT_ID,
    MARKS,
    CASE
        WHEN MARKS >= 85 THEN 'DISTINCTION'
        WHEN MARKS >= 60 THEN 'PASS'
        ELSE 'FAIL'
    END AS RESULT
FROM ENROLLMENT;

SELECT COUNT(*) AS TOTAL_STUDENTS
FROM STUDENT;

SELECT COUNT(*) AS TOTAL_ENROLLMENTS
FROM ENROLLMENT;

SELECT
    SUM(MARKS) AS TOTAL_MARKS,
    AVG(MARKS) AS AVERAGE_MARKS,
    MAX(MARKS) AS HIGHEST_MARKS,
    MIN(MARKS) AS LOWEST_MARKS
FROM ENROLLMENT;

SELECT
    CITY,
    COUNT(*) AS STUDENT_COUNT
FROM STUDENT
GROUP BY CITY;

SELECT
    DEPT_ID,
    COUNT(*) AS STUDENT_COUNT
FROM STUDENT
GROUP BY DEPT_ID;

SELECT
    COURSE_ID,
    AVG(MARKS) AS AVERAGE_MARKS
FROM ENROLLMENT
GROUP BY COURSE_ID;

SELECT
    DEPT_ID,
    AVG(SALARY) AS AVERAGE_SALARY
FROM FACULTY
GROUP BY DEPT_ID;

SELECT
    COURSE_ID,
    AVG(MARKS) AS AVERAGE_MARKS
FROM ENROLLMENT
GROUP BY COURSE_ID
HAVING AVG(MARKS) > 75;

SELECT
    S.STUDENT_NAME,
    E.COURSE_ID,
    E.MARKS
FROM STUDENT S
INNER JOIN ENROLLMENT E
ON S.STUDENT_ID = E.STUDENT_ID;

SELECT
    S.STUDENT_NAME,
    C.COURSE_NAME,
    D.DEPT_NAME
FROM STUDENT S
INNER JOIN DEPARTMENT D
ON S.DEPT_ID = D.DEPT_ID
INNER JOIN ENROLLMENT E
ON S.STUDENT_ID = E.STUDENT_ID
INNER JOIN COURSE C
ON E.COURSE_ID = C.COURSE_ID;

SELECT
    F.FACULTY_NAME,
    F.DESIGNATION,
    D.DEPT_NAME
FROM FACULTY F
INNER JOIN DEPARTMENT D
ON F.DEPT_ID = D.DEPT_ID;

SELECT
    C.COURSE_NAME,
    F.FACULTY_NAME,
    E.STUDENT_ID,
    E.MARKS
FROM ENROLLMENT E
INNER JOIN COURSE C
ON E.COURSE_ID = C.COURSE_ID
INNER JOIN FACULTY F
ON C.FACULTY_ID = F.FACULTY_ID;

SELECT
    S.STUDENT_NAME,
    E.COURSE_ID,
    E.MARKS
FROM STUDENT S
LEFT JOIN ENROLLMENT E
ON S.STUDENT_ID = E.STUDENT_ID;

SELECT
    D.DEPT_NAME,
    F.FACULTY_NAME,
    F.DESIGNATION
FROM DEPARTMENT D
LEFT JOIN FACULTY F
ON D.DEPT_ID = F.DEPT_ID;

SELECT
    STUDENT_ID,
    COURSE_ID,
    MARKS,
    RANK() OVER (
        ORDER BY MARKS DESC
    ) AS MARKS_RANK
FROM ENROLLMENT;

SELECT
    STUDENT_ID,
    COURSE_ID,
    MARKS,
    ROW_NUMBER() OVER (
        ORDER BY MARKS DESC
    ) AS ROW_NUMBER
FROM ENROLLMENT;

SELECT
    E.STUDENT_ID,
    E.COURSE_ID,
    E.MARKS,
    RANK() OVER (
        PARTITION BY E.COURSE_ID
        ORDER BY E.MARKS DESC
    ) AS COURSE_RANK
FROM ENROLLMENT E;

SELECT
    ENROLLMENT_ID,
    ENROLL_DATE,
    MARKS,
    SUM(MARKS) OVER (
        ORDER BY ENROLL_DATE, ENROLLMENT_ID
    ) AS RUNNING_TOTAL
FROM ENROLLMENT;

SELECT
    ENROLLMENT_ID,
    ENROLL_DATE,
    MARKS,
    LAG(MARKS) OVER (
        ORDER BY ENROLL_DATE, ENROLLMENT_ID
    ) AS PREVIOUS_MARKS
FROM ENROLLMENT;

WITH COURSE_AVG AS (
    SELECT
        COURSE_ID,
        AVG(MARKS) AS AVERAGE_MARKS
    FROM ENROLLMENT
    GROUP BY COURSE_ID
)
SELECT *
FROM COURSE_AVG;

WITH STUDENT_TOTAL AS (
    SELECT
        STUDENT_ID,
        SUM(MARKS) AS TOTAL_MARKS
    FROM ENROLLMENT
    GROUP BY STUDENT_ID
)
SELECT
    S.STUDENT_NAME,
    T.TOTAL_MARKS
FROM STUDENT S
JOIN STUDENT_TOTAL T
ON S.STUDENT_ID = T.STUDENT_ID;

WITH DEPT_SALARY AS (
    SELECT
        DEPT_ID,
        AVG(SALARY) AS AVERAGE_SALARY
    FROM FACULTY
    GROUP BY DEPT_ID
)
SELECT
    D.DEPT_NAME,
    DS.AVERAGE_SALARY
FROM DEPARTMENT D
JOIN DEPT_SALARY DS
ON D.DEPT_ID = DS.DEPT_ID;

WITH STUDENT_TOTAL AS (
    SELECT
        STUDENT_ID,
        SUM(MARKS) AS TOTAL_MARKS
    FROM ENROLLMENT
    GROUP BY STUDENT_ID
)
SELECT
    S.STUDENT_NAME,
    D.DEPT_NAME,
    NVL(T.TOTAL_MARKS, 0) AS TOTAL_MARKS
FROM STUDENT S
JOIN DEPARTMENT D
ON S.DEPT_ID = D.DEPT_ID
LEFT JOIN STUDENT_TOTAL T
ON S.STUDENT_ID = T.STUDENT_ID;
